name: SalesforceBrowser
version: 0.0.1
description: A starter template for a polymer.dart web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  paper_elements: '>=0.7.0 <0.8.0'
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
